# ${varName : defaultValue}  -> environment variable
spring.application.name= ${SPRING_APP_NAME:securitypart1}

#spring.security.user.name=${SECURITY_USERNAME:admin}
#spring.security.user.password=${SECURITY_PASSWORD:admin123}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/springsecurity_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.format_sql = true
spring.jpa.hibernate.show_sql = true
spring.jpa.hibernate.ddl-auto = update


###
# (1) Encoding vs Encryption vs Hashing
# (2) Drawbacks of Hashing & How to overcome Hashing drawbacks
# (3) Spring's "Password Encoder" and its' implementations
# (4) Understand "Authentication Provider"
# (5) Implementing and Customizing the AuthenticationProvider inside our application
#   (5.1) create "MyUsernamePwdAuthenticationProvider" class in "config" package
# (6) Testing
###


