# ${varName : defaultValue}  -> environment variable
spring.application.name= ${SPRING_APP_NAME:securitypart1}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/springsecurity_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.format_sql = true
spring.jpa.hibernate.show_sql = true
spring.jpa.hibernate.ddl-auto = update

spring.config.import = application_prod.properties
# default | prod
spring.profiles.active = default

###
# Exception Handling with security
# (1) AuthenticationEntryPoint: "Authentication failed"
#   - If user try to login but failed, we can modify the response
#   -   using "AuthenticationEntryPoint" class
#   (1.1) create "CustomBasicAuthenticationEntryPoint" class
#   (1.2) on security-config-classes: 
#       (1.2.1) edit "http.httpBasic()" -> defaultSecurityFilterChain()
#       (1.2.2) add "http.exceptionHandling()"
# (2) AccessDenied: "Authorization Failed"
#   (2.1) create "CustomAccessDeniedHandler" class
#   (2.2) on security-config-classes: 
#       (2.2.1) add "http.exceptionHandling()"
###


