spring.application.name=ssecurity_OAuth2_23


spring.security.user.name=${SECURITY_USERNAME:hegazy}
spring.security.user.password=${SECURITY_PASSWORD:12345}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

# OAuth configs
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liOUPZnJim5TDE8w}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:83c1d907516bc3096dfb5d85967cff3eddda16ee}

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID:690404263961116}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET:2ad005ba2617f03be1e5253c012c7102}


###
#TODO Steps (1) :-
##
#1. comment {clientRegistrationRepository(), githubClientRegistration(), facebookClientRegistration()}
#2. add props in application.properties 
#   {
#       .oauth2.client.registration.github.client-id,
#       .oauth2.client.registration.github.client-secret
#       .oauth2.client.registration.facebook.client-id,
#       .oauth2.client.registration.facebook.client-secret
#   }
#!3. Testing the app {github, facebook} social login works fine
#

###




