# ${varName : defaultValue}  -> environment variable
spring.application.name= ${SPRING_APP_NAME:spring-security-jwt-20}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/springsecurity_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.format_sql = true
spring.jpa.hibernate.show_sql = true
spring.jpa.hibernate.ddl-auto = update

spring.config.import = application_prod.properties

# default | prod
spring.profiles.active = default

server.servlet.session.timeout = ${SESSION_TIMEOUT:20m}

logging.level.org.springframework.security.web.FilterChainProxy = debug

###
# * JWT: JSON Web Token
#  - It is a token implementation which will be in the JSON format
#
# * Until now we have 2 tokens {JSESSION, XSRF-TOKEN}
# * But now we will use JWT because it is stateless and can be used in microservices because it is self-contained
#   - it is signed and can be verified by the server
#   - it is not stored in the session, so it can be used in a stateless way
#   - Used with distributed systems where quick access to user information is needed
#       without querying the database / server
#
# * JWT vs Opaque Token:
#   - Opaque Token: the server stores the token in the session and can verify it
#   - JWT: the token is self-contained, it contains all the information needed to verify
#
# * JWT Token Advantages:
#   - Statelessness
#   - Self-contained: it stores info about the user and the roles
#   - Security
#   - Expiration
#   - Reusability: can be used in different services by Single-Sign-On {SSO}
#   - Crosss-PLatform compatibility
#
# * JWT Structure:
#   - Header: contains the type of token and the signing algorithm
#       - the algorithm that is used to generate the signature
#       - e.g., {"alg": "HS256", "typ": "JWT"}
#   - Payload: contains the claims (user information, roles, etc.)
#   - Signature: used to verify the token
#       - created by signing the header and payload with a secret key
#       ! algorithm-signing( encode-header + "." + encode-payload, secret-key )
#       - e.g., HMACSHA256(base64UrlEncode(header) + "." + base64UrlEncode(payload), secret)
#
# * JWT Claims:
#   - Registered Claims: predefined claims like iss (issuer), exp (expiration), sub (subject), aud (audience)
#   - Public Claims: custom claims that can be defined by the user
#   - Private Claims: custom claims that are used only by the application
#
# * JWT Usage:
#   - Used in APIs to authenticate users
#   - Used in OAuth2 and OpenID Connect to authenticate users
#   - Used in social login to authenticate users
#   - Used in Single Sign-On (SSO) to authenticate users across different applications
#   - Used in distributed systems to authenticate users
#   - Used in microservices to authenticate users
#   - Used in social login to authenticate users
#
# * JWT Security:
#   - Use strong secret keys to sign the tokens
#   - Use HTTPS to encrypt the tokens in transit
#   - Use short expiration times for the tokens
#   - Use refresh tokens to renew the access tokens
#   - Use token revocation to invalidate the tokens
#   - Use token blacklisting to invalidate the tokens
#   - Use token whitelisting to allow only certain tokens
#   - Use token introspection to verify the tokens
#   - Use token validation to verify the tokens
#   - Use token encryption / decryption to encrypt / decrypt the tokens
#   - Use token signing / verification to sign / verify the tokens
#   - Use token serialization / deserialization to serialize / deserialize the tokens
#   - Use token compression / decompression to compress / decompress the tokens
#   - Use token encoding / decoding to encode / decode the tokens
#   - Use token hashing / unhashing to hash / unhash the tokens
#
# * https://www.jwt.io/
#
# ! JWT implementation:
# * Steps (1):
# (1) add dependencies for JWT
#   - io.jsonwebtoken : jjwt-api : 0.12.5
#   - io.jsonwebtoken : jjwt-impl : 0.12.5 : scope -> runtime
#   - io.jsonwebtoken : jjwt-jackson : 0.12.5 : scope -> runtime
#
# (2) in security-config-class: 
#   - change "http.sessionManagement()" that is responsiple on creating JSESSIONIDfrom from "ALWAYS" to "STATELESS"
#   - no need for "http.securityContext()" because we are not using session
#   - in CORS config: use "config.setExposedHeaders(Arrays.asList("Authorization"))" to expose the JWT token in the response header
#
# (3) create "JWTTokenGeneratorFilter" class in "filter" package
#
# (4) create "JWTTokenValidatorFilter" class in "filter" package
#
# (5) in security-config-class:
#   - add "http.addFilterAfter(new JWTTokenGeneratorFilter(), BasicAuthenticationFilter.class
#       - this will add the filter after the BasicAuthenticationFilter to generate the JWT token
#   - add "http.addFilterBefore(new JWTTokenValidatorFilter(), BasicAuthenticationFilter.class)"
#       - this will add the filter before the BasicAuthenticationFilter to validate the JWT token
#       - this filter will check if the request has a JWT token in the header
#       - if the token is valid, it will set the authentication in the security context
#       - if the token is invalid, it will throw an exception
# (6) create "constants" package
#
# (7) create "ApplicationContants" class
#
# (8) implement "doFilterInternal()" in "JWTTokenGeneratorFilter" class
#
# (9) implement "doFilterInternal()" in "JWTTokenValidatorFilter" class
#
# (10) some changes on UI side
#
# ! Testing (1):
#   - use Postman to test the JWT token generation and validation
#   - (1) endpoint 1: /user
#   - Request: GET "http://localhost:8080/user"  + {username, password}
#   - Response: 
#   ```
#       - 200 OK
#       - {
#           "id": 1,
#           "name": "user1",
#           "email": "user1@gmail.com",
#           "mobileNumber": "01001775021",
#           "role": "admin"
#         }
#       - Headers: {"Authorization", "JWT_Token"}
#   ```
#   - (2) endpoint 2:
#   - Request: GET "http://localhost:8080/myAccount?id=1"  + No-Auth + Headers_{"Authorization", "JWT_Token"}
#   - Response: 
#   ```
#       - 200 OK
#       - {
#           "customerId": 1,
#           "accountNumber": 1865764534,
#           "accountType": "Savings",
#           "branchAddress": "123 Main Street, New York",
#           "createDt": null
#         }
#   ```
#
# * Steps (2):
# - create "dto" package
# - create "LoginRequestDTO" class
# - create "LoginResponseDTO" class
# - "UserController" class: implement "apiLogin()" "/apiLogin" endpoint
# - "security-config" class: 
#   - implement "@Bean authenticationManager()"
#   - add "/apiLogin" to the allowed endpoints
#
# # ! Testing (2):
#   - use Postman to test the JWT token generation and validation
#   - (1) endpoint 1: /apiLogin
#   - Request: POST "http://localhost:8080/apiLogin"
#       {
#           "username": "user1@gmail.com",
#           "password": "User_12345@@"
#       }
#   - Response: 
#   ```
#       - 200 OK
#       - {
#           "status": "OK",
#           "jwtToken": "eyJhbGciOiJIUzI1..."
#         }
#   ```
###

