spring.application.name=ssecurity_OAuth2_23


spring.security.user.name=${SECURITY_USERNAME:hegazy}
spring.security.user.password=${SECURITY_PASSWORD:12345}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

# spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liCBLLUjii41pS7k}
# spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:9da8734b56aad52d91b268fe6834a8df12447d95}

# spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID:974042741122392}
# spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET:36d48c25c1767d58b3101551513d7e1e}


###
#TODO Steps (1) :-
##
#1. create app on start.spring.io
#2. add dependencies {web, security, devtools, OAuth2 Client, OAuth2 Resource Server}
#3. create "controller" package + "SecureController" class
#   3.1. implement "@GetMapping("/secure")" method
#   ```
#       @GetMapping("/secure")
#       public String securePage() {
#            return "secure.html";
#       }
#   ```
#4. create "secure.html" page
#5. add props in application.properties {security, logging}
#!6. Testing: "http://localhost:8080/secure?continue" {username, password}
##
#TODO Steps (2) :-
##
#7. Create "config" package & "ProjectSecurityConfig" class
#8. Implement "defaultSecurityFilterChain()" bean
#9. Implement "clientRegistrationRepository()" bean : {github, facebook}
#10. Implement {github, facebook} ClientRegistration:
#   10.1. Implement "githubClientRegistration()"
#   10.2. Implement "facebookClientRegistration()"
#11. use your ClientRegistration_s in "clientRegistrationRepository()" bean
#12. get {clientId, clientSecret} for "github"
#   12.1. open "github.com" ->> settings ->> developer settings
#       ->> oauth apps ->> create new app
#           {HegazyOAuth2App, http://localhost:8080, http://localhost:8080}
#           = so you will get the required info
#   12.2 add the info to "ClientRegisteration_s"
#13. get {clientId, clientSecret} for "facebook"
#   13.1. open "developers.facebook.com" ->> create new app
#   13.2 login
#   13.3 create app {HegazyOAuth2App, ...info}
#   13.4 on the app ->> open use_cases ->> customize / edit ->> add "email" scope
#   13.5 open app_settings ->> click "basic" ->> get {clientId, clientSecret}
#14. apply configs on "oauth2" ->> ``` http.oauth2Login(oauth2 -> oauth2.defaultSuccessUrl("/secure", true)); ```
#!15. Testing: you will see 2 options for "github" & "facebook"
##
#TODO Steps (3) :-
##
#16. add new param in "@GetMapping("/secure")" method ->> "authentication"
#   16.1 refactor "@GetMapping("/secure")" method: logging the authentication object
#
###




