# ${varName : defaultValue}  -> environment variable
spring.application.name= ${SPRING_APP_NAME:securitypart1}

logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3307/springsecurity_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.format_sql = true
spring.jpa.hibernate.show_sql = true
spring.jpa.hibernate.ddl-auto = update

spring.config.import = application_prod.properties

# default | prod
spring.profiles.active = default

server.servlet.session.timeout = ${SESSION_TIMEOUT:20m}

###
# ? Spring Security Form Login Configuration:
# ! Steps:
#   (1) create "@Controller HomeController" class
#   (2) create "home.html" page that supports thymeleaf
#   (3) add "/" for "home.html" in the allowed endpoint in the security-config-class
#   (4) add "thymeleaf" dependency + run "mvn clean install"
#   *(5) Testing: some endpoints are accessable, other redirect to the default login page
#   (6) Login Functionality :-
#       (6.1) create custom "login.html" page
#       (6.2) on security-config-class: edit "http.formLogin(form -> form.loginPage("/login"))"
#       (6.3) create "@Controller LoginController" class
#   (7) Logout Functionality :-
#       (7.1) add the "logout" in "home.html" page
#       (7.2) add the "logout" config in security-config-classes
#       (7.3) add the "/logout" into the allowed endpoints
#   (8) Show Username and Login State in Header :-
#       (8.1) add "thymeleaf-extras-springsecurity6" dependency
#       (8.2) add the xmlns related to the added dependency in the "home.html" page
#       (8.3) use thymeleaf-ssecurity into "home.html", "login.html" to control when to show username/login-link
#               based on user is login or not
###


